name: cat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - augustus=3.3.3
  - bamtools=2.5.1
  - bcbio-gff=0.6.6
  - biopython=1.76
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bx-python=0.8.8
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cdbtools=0.99
  - certifi=2019.11.28
  - configobj=5.0.6
  - curl=7.68.0
  - cycler=0.10.0
  - dbus=1.13.6
  - diamond=0.9.30
  - docutils=0.16
  - ete3=3.1.1
  - exonerate=2.4.0
  - expat=2.2.9
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gsl=2.5
  - htslib=1.9
  - icu=64.2
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libbigwig=0.4.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libcxx=9.0.1
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libpq=12.2
  - libssh2=1.8.2
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=9.0.1
  - lockfile=0.12.2
  - lp_solve=5.5.2.5
  - luigi=2.8.12
  - lxml=4.5.0
  - lzo=2.10
  - matplotlib-base=3.2.1
  - metis=5.1.0
  - mysql-connector-c=6.1.11
  - ncurses=6.1
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.1
  - openblas=0.3.6
  - openssl=1.1.1f
  - pandas=1.1.0
  - parasail-python=1.2
  - patsy=0.5.1
  - pcre=8.44
  - perl=5.26.2
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-base=2.23
  - perl-carp=1.38
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-constant=1.33
  - perl-cpan-meta=2.150010
  - perl-cpan-meta-requirements=2.140
  - perl-cpan-meta-yaml=0.018
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-dbi=1.642
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.04
  - perl-dist-checkconflicts=0.11
  - perl-encode=2.88
  - perl-eval-closure=0.14
  - perl-exporter=5.72
  - perl-extutils-cbuilder=0.280230
  - perl-extutils-makemaker=7.36
  - perl-extutils-manifest=1.72
  - perl-extutils-parsexs=3.35
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-file-which=1.23
  - perl-getopt-long=2.50
  - perl-ipc-cmd=1.02
  - perl-json-pp=4.04
  - perl-locale-maketext-simple=0.21
  - perl-module-build=0.4224
  - perl-module-corelist=5.20190524
  - perl-module-implementation=0.09
  - perl-module-load=0.32
  - perl-module-load-conditional=0.68
  - perl-module-metadata=1.000036
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mro-compat=0.13
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-parallel-forkmanager=2.02
  - perl-params-check=0.38
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-perl-ostype=1.010
  - perl-role-tiny=2.000008
  - perl-scalar-list-utils=1.52
  - perl-storable=3.15
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006003
  - perl-text-abbrev=1.02
  - perl-text-parsewords=3.30
  - perl-try-tiny=0.30
  - perl-version=0.9924
  - perl-xsloader=0.24
  - perl-yaml=1.29
  - pip=20.0.2
  - prometheus_client=0.5.0
  - pthread-stubs=0.4
  - pyfasta=0.5.2
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pysam=0.15.3
  - python=3.7.6
  - python-daemon=2.2.4
  - python-dateutil=2.8.1
  - python-lzo=1.12
  - python_abi=3.7
  - pytz=2019.3
  - qt=5.12.5
  - readline=8.0
  - samtools=1.9
  - scipy=1.4.1
  - seaborn=0.12.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlalchemy=1.3.15
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - suitesparse=5.6.0
  - tbb=2019.9
  - tk=8.6.10
  - toml=0.10.0
  - tornado=5.1.1
  - ucsc-axtchain=366
  - ucsc-bamtopsl=377
  - ucsc-bedsort=377
  - ucsc-bedtobigbed=366
  - ucsc-chainmergesort=366
  - ucsc-fatotwobit=377
  - ucsc-genepredtobed=377
  - ucsc-genepredtofakepsl=366
  - ucsc-genepredtogtf=377
  - ucsc-gff3togenepred=366
  - ucsc-gtftogenepred=377
  - ucsc-pslcdnafilter=366
  - ucsc-pslmap=366
  - ucsc-pslmappostchain=366
  - ucsc-pslpostarget=366
  - ucsc-pslrecalcmatch=366
  - ucsc-psltobigpsl=377
  - ucsc-transmappsltogenepred=366
  - ucsc-twobitinfo=366
  - wheel=0.34.2
  - wiggletools=1.2.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
