#!/usr/bin/env python
import argparse
from BCBio import GFF
from collections import Counter, OrderedDict


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('input_gff3', help='Prokka GFF3 file')
    parser.add_argument('output_gff3', help='Output GFF3')
    return parser.parse_args()


def add_tags_to_feature(feature, lt_counts):
    if 'locus_tag' not in feature.qualifiers:
        return
    feature.qualifiers['gene_id'] = [feature.qualifiers['locus_tag'][0]]
    feature.qualifiers['gene_name'] = [feature.qualifiers.get('gene', feature.qualifiers['gene_id'])[0]]
    if feature.type in ['CDS', 'ncRNA', 'tRNA', 'rRNA']:
        feature.qualifiers['transcript_id'] = ['{}-{}'.format(feature.qualifiers['locus_tag'][0],
                                                              lt_counts[feature.qualifiers['locus_tag'][0]])]
        feature.qualifiers['transcript_name'] = ['{}-{}-{}'.format(feature.qualifiers['gene_name'][0],
                                                                   feature.qualifiers['locus_tag'][0],
                                                                   lt_counts[feature.qualifiers['locus_tag'][0]])]
        if feature.type == 'CDS':
            biotype = ['protein_coding']
        else:
            biotype = [feature.type]
        feature.qualifiers['gene_biotype'] = feature.qualifiers['transcript_biotype'] = biotype
        lt_counts[feature.qualifiers['locus_tag'][0]] += 1


def construct_new_qualifiers(feature):
    new_qualifiers = OrderedDict()
    for key, val in feature.qualifiers.items():
        # no upper case keys unless it is ID or Parent or Name
        if key not in ['ID', 'Parent', 'Name']:
            key = key.lower()
        # collapse to a single item
        # replace all semicolons
        if len(val) > 1:
            val = [' '.join([x.replace(';', '%3B') for x in val])]
        new_qualifiers[key] = val
    # clean up and make parseable
    for key, val in new_qualifiers.items():
        if sum(len(x) for x in val) == 0:
            new_qualifiers[key] = 'True'
    return new_qualifiers


def feature_traversal(feature):
    yield feature
    for sub_feature in feature.sub_features:
        yield from feature_traversal(sub_feature)


if __name__ == '__main__':
    args = parse_args()
    lt_counts = Counter()
    records = list(GFF.parse(args.input_gff3))
    for seqrecord in records:
        for parent_feature in seqrecord.features:
            for feature in feature_traversal(parent_feature):
                try:
                    add_tags_to_feature(feature, lt_counts)
                except KeyError:
                    assert False, feature.qualifiers
                new_qualifiers = construct_new_qualifiers(feature)
                feature.qualifiers = new_qualifiers

    with open(args.output_gff3, 'w') as fh:
        GFF.write(records, fh)
